#!/bin/bash
# Description: install utils (need to re-login for environment effective)
echo "Setting up utils"
# Description: Dir setup and File registration
for dir in bin .var/cache .var/log .trash; do
    mkdir -p "$HOME/$dir"
done
PATH=$HOME/bin:$PATH
cd ~/utils/bin
. func.link.sh
_setup_link
. rc.bash
link-self
bashrc-setup
echo "You need [pkg init] and [db-update -f]"
