#!/bin/bash
# Description: install utils (need to re-login for environment effective)
echo "Setting up utils"
# Description: Dir setup and File registration
for dir in bin  .trash .var/cache .var/log; do
    mkdir -p "$HOME/$dir"
done
PATH=$HOME/bin:$PATH
cd ~/utils/bin
git config credential.helper store
. func.link.sh
_setup_link
. rc.bash
file-link
bashrc-setup
# Git setting
git config --global push.default matching
git config --global credential.helper store
for n in name email; do
    git config user.$n || git config --global user.$n "$USER@$HOSTNAME"
done
pkg(){
    echo "You need register /sbin first"
    file-register ~/utils/sbin
}
echo "You need [pkg init] and [db-update -f]"
